revert changes to bin/container_daemon

diff --git a/bin/container_daemon b/bin/container_daemon
--- a/bin/container_daemon
+++ b/bin/container_daemon
@@ -11,10 +11,19 @@ if [ `id -u` -eq 0 ]; then
   exec su-exec "$user" "$0" "$@"
 fi
 
-# if the first argument is daemon
-if [ "$1" = "daemon"] || ["$1" = "init"] ; then
-  exec go-filecoin "$1" "$@"
+if [ -e "$repo/config" ]; then
+  echo "Found Filecoin fs-repo at $repo"
 else
-  echo "ERROR: arguments have been set but the first argument isn't 'init' or 'daemon'" >&2
+  go-filecoin init
+  # TODO configure custom API and address here
 fi
+
+# if the first argument is daemon
+if [ "$1" = "daemon" ]; then
+  shift
+else
+  echo "ERROR: arguments have been set but the first argument isn't 'daemon'" >&2
+fi
+
+exec go-filecoin daemon "$@"
 
