upgrade to latest version

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,7 +29,7 @@ jobs:
   build_macos:
     macos:
       xcode: "10.0.0"
-    working_directory: ~/go/src/github.com/filecoin-project/go-filecoin
+    working_directory: ~/go/src/github.com/filecoin-project/venus
     resource_class: large
     steps:
       - run:
@@ -40,23 +40,21 @@ jobs:
             echo 'source $BASH_ENV' >> $HOME/.bashrc
       - add_ssh_keys:
           fingerprints:
-              - "1e:73:c5:15:75:e0:e4:98:54:3c:2b:9e:e8:94:14:2e"
+            - "1e:73:c5:15:75:e0:e4:98:54:3c:2b:9e:e8:94:14:2e"
       - checkout
       - update_submodules
       - generate_rust_submodules_checksums
       - restore_cache:
-          key: v9-go-deps-{{ arch }}-{{ checksum  "~/go/src/github.com/filecoin-project/go-filecoin/build/main.go" }}-{{ checksum "~/go/src/github.com/filecoin-project/go-filecoin/go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
+          key: v9-go-deps-{{ arch }}-{{ checksum  "~/go/src/github.com/filecoin-project/venus/build/main.go" }}-{{ checksum "~/go/src/github.com/filecoin-project/venus/go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       # The second checkout ensures we have the most recent code since the
-      # restore_cache step above can override the go-filecoin code with cached code
+      # restore_cache step above can override the venus code with cached code
       - git_fetch_all_tags
       - checkout
-      - restore_cache:
-          key: v26.0-proof-params-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       - run:
           name: Install go
           command: |
-            curl -O https://dl.google.com/go/go1.13.4.darwin-amd64.pkg && \
-            sudo installer -pkg go1.13.4.darwin-amd64.pkg -target /
+            curl -O https://dl.google.com/go/go1.14.4.darwin-amd64.pkg && \
+            sudo installer -pkg go1.14.4.darwin-amd64.pkg -target /
       - run:
           name: Install pkg-config
           command: HOMEBREW_NO_AUTO_UPDATE=1 brew install pkg-config
@@ -80,11 +78,7 @@ jobs:
       # groth parameters are generated by the paramcache binary, run as part
       # of both deps and smartdeps commands
       - save_cache:
-          key: v26.0-proof-params-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
-          paths:
-            - "~/filecoin-proof-parameters/"
-      - save_cache:
-          key: v9-go-deps-{{ arch }}-{{ checksum  "~/go/src/github.com/filecoin-project/go-filecoin/build/main.go" }}-{{ checksum "~/go/src/github.com/filecoin-project/go-filecoin/go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
+          key: v9-go-deps-{{ arch }}-{{ checksum  "~/go/src/github.com/filecoin-project/venus/build/main.go" }}-{{ checksum "~/go/src/github.com/filecoin-project/venus/go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
           paths:
             - "~/go/pkg"
             - "~/go/src/gx"
@@ -108,7 +102,7 @@ jobs:
           name: Create macos bundle
           command: ./scripts/build-bundle.sh
       - store_artifacts:
-          path: "~/go/src/github.com/filecoin-project/go-filecoin/bundle/"
+          path: "~/go/src/github.com/filecoin-project/venus/bundle/"
           destination: bundle
       - store_test_results:
           path: test-results
@@ -119,8 +113,8 @@ jobs:
 
   deps_linux:
     docker:
-      - image: circleci/golang:1.13.1-stretch
-    working_directory: /go/src/github.com/filecoin-project/go-filecoin
+      - image: circleci/golang:1.14.1-stretch
+    working_directory: /go/src/github.com/filecoin-project/venus
     resource_class: xlarge
     steps:
       - linux_configure
@@ -140,11 +134,9 @@ jobs:
             - v9-go-deps-{{ .Branch }}-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
             - v9-go-deps-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       # The second checkout ensures we have the most recent code since the
-      # restore_cache step above can override the go-filecoin code with cached code
+      # restore_cache step above can override the venus code with cached code
       - git_fetch_all_tags
       - checkout
-      - restore_cache:
-          key: v26.0-proof-params-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       - run:
           name: Install Rust toolchain (for rust-fil-proofs)
           command: |
@@ -154,10 +146,6 @@ jobs:
           no_output_timeout: "60m"
       # groth parameters are generated by the paramcache binary, run as part
       # of both deps and smartdeps commands
-      - save_cache:
-          key: v26.0-proof-params-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
-          paths:
-            - "/home/circleci/filecoin-proof-parameters/"
       - save_cache:
           key: v9-go-deps-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
           paths:
@@ -179,8 +167,8 @@ jobs:
 
   build_linux:
     docker:
-      - image: circleci/golang:1.13.1-stretch
-    working_directory: /go/src/github.com/filecoin-project/go-filecoin
+      - image: circleci/golang:1.14.1-stretch
+    working_directory: /go/src/github.com/filecoin-project/venus
     resource_class: xlarge
     parameters:
       <<: *nightly_param
@@ -198,11 +186,9 @@ jobs:
             - v9-go-deps-{{ .Branch }}-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
             - v9-go-deps-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       # The second checkout ensures we have the most recent code since the
-      # restore_cache step above can override the go-filecoin code with cached code
+      # restore_cache step above can override the venus code with cached code
       - git_fetch_all_tags
       - checkout
-      - restore_cache:
-          key: v26.0-proof-params-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       - go_build:
           cmd: "lint"
       - go_build:
@@ -218,7 +204,7 @@ jobs:
           name: Create linux bundle
           command: ./scripts/build-bundle.sh
       - store_artifacts:
-          path: "/go/src/github.com/filecoin-project/go-filecoin/bundle/"
+          path: "/go/src/github.com/filecoin-project/venus/bundle/"
           destination: bundle
       - when:
           condition: << parameters.nightly >>
@@ -230,14 +216,14 @@ jobs:
             - "bundle/"
             - "tools/gengen/gengen"
             - "fixtures"
-            - "go-filecoin"
+            - "venus"
             - "tools"
 
   unit_test_linux:
     docker:
-      - image: circleci/golang:1.13.1-stretch
+      - image: circleci/golang:1.14.1-stretch
     parallelism: 2 # Check .codecov.yml "after_n_builds" if changing this
-    working_directory: /go/src/github.com/filecoin-project/go-filecoin
+    working_directory: /go/src/github.com/filecoin-project/venus
     resource_class: xlarge
     steps:
       - linux_configure
@@ -253,11 +239,11 @@ jobs:
             - v9-go-deps-{{ .Branch }}-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
             - v9-go-deps-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       # The second checkout ensures we have the most recent code since the
-      # restore_cache step above can override the go-filecoin code with cached code
+      # restore_cache step above can override the venus code with cached code
       - git_fetch_all_tags
       - checkout
-      - restore_cache:
-          key: v26.0-proof-params-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
+      - go_build:
+          cmd: "build"
       - mkdir_test_results
       - go_test:
           functional: false
@@ -267,9 +253,9 @@ jobs:
 
   integration_test_linux:
     docker:
-      - image: circleci/golang:1.13.1-stretch
+      - image: circleci/golang:1.14.1-stretch
     parallelism: 2 # Check .codecov.yml "after_n_builds" if changing this
-    working_directory: /go/src/github.com/filecoin-project/go-filecoin
+    working_directory: /go/src/github.com/filecoin-project/venus
     resource_class: xlarge
     steps:
       - linux_configure
@@ -285,11 +271,11 @@ jobs:
             - v9-go-deps-{{ .Branch }}-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
             - v9-go-deps-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       # The second checkout ensures we have the most recent code since the
-      # restore_cache step above can override the go-filecoin code with cached code
+      # restore_cache step above can override the venus code with cached code
       - git_fetch_all_tags
       - checkout
-      - restore_cache:
-          key: v26.0-proof-params-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
+      - go_build:
+          cmd: "build"
       - attach_workspace:
           at: "."
       - mkdir_test_results
@@ -301,9 +287,9 @@ jobs:
 
   functional_test_linux:
     docker:
-      - image: circleci/golang:1.13.1-stretch
+      - image: circleci/golang:1.14.1-stretch
     parallelism: 2
-    working_directory: /go/src/github.com/filecoin-project/go-filecoin
+    working_directory: /go/src/github.com/filecoin-project/venus
     resource_class: xlarge
     parameters:
       <<: *sector_builder_tests_param
@@ -321,11 +307,11 @@ jobs:
             - v9-go-deps-{{ .Branch }}-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
             - v9-go-deps-{{ arch }}-{{ checksum  "build/main.go" }}-{{ checksum "go.mod" }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       # The second checkout ensures we have the most recent code since the
-      # restore_cache step above can override the go-filecoin code with cached code
+      # restore_cache step above can override the venus code with cached code
       - git_fetch_all_tags
       - checkout
-      - restore_cache:
-          key: v26.0-proof-params-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
+      - go_build:
+          cmd: "build"
       - attach_workspace:
           at: "."
       - mkdir_test_results
@@ -339,7 +325,7 @@ jobs:
 
   publish_release:
     docker:
-      - image: circleci/golang:1.13.1-stretch
+      - image: circleci/golang:1.14.1-stretch
     resource_class: small
     parameters:
       <<: *nightly_param
@@ -365,7 +351,7 @@ jobs:
 
   build_docker_img:
     docker:
-      - image: circleci/golang:1.13.1-stretch
+      - image: circleci/golang:1.14.1-stretch
     resource_class: xlarge
     parameters:
       <<: *nightly_param
@@ -395,8 +381,6 @@ jobs:
       - generate_rust_submodules_checksums
       - attach_workspace:
           at: "."
-      - restore_cache:
-          key: v26.0-proof-params-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       - run:
           name: build a base image
           command: |
@@ -438,8 +422,6 @@ jobs:
               docker tag 657871693752.dkr.ecr.us-east-1.amazonaws.com/filecoin-faucet:$SHORT_GIT_SHA 657871693752.dkr.ecr.us-east-1.amazonaws.com/filecoin-faucet:${FILECOIN_BINARY_VERSION}
               docker push 657871693752.dkr.ecr.us-east-1.amazonaws.com/filecoin-faucet:${FILECOIN_BINARY_VERSION}
             fi
-      - restore_cache:
-          key: v26.0-proof-params-large-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
       - run:
           name: build & push image - filecoin
           command: |
@@ -456,14 +438,10 @@ jobs:
               docker tag 657871693752.dkr.ecr.us-east-1.amazonaws.com/filecoin:$SHORT_GIT_SHA 657871693752.dkr.ecr.us-east-1.amazonaws.com/filecoin:${FILECOIN_BINARY_VERSION}
               docker push 657871693752.dkr.ecr.us-east-1.amazonaws.com/filecoin:${FILECOIN_BINARY_VERSION}
             fi
-      - save_cache:
-          key: v26.0-proof-params-large-{{ arch }}-{{ checksum "/tmp/filecoin-ffi-checksum.txt" }}
-          paths:
-            - "./filecoin-proof-parameters/"
 
   trigger_nightly_devnet_deploy:
     docker:
-      - image: circleci/golang:1.13.1-stretch
+      - image: circleci/golang:1.14.1-stretch
     resource_class: small
     steps:
       - setup_remote_docker
@@ -480,7 +458,7 @@ jobs:
             git config user.email dev-helper@filecoin.io
             git config user.name filecoin-helper
             git tag -f -a ${FILECOIN_BINARY_VERSION} -m "$(date -u '+%Y-%m-%dT%H:%M:%S%z')"
-            git push -f https://${GITHUB_TOKEN}@github.com/filecoin-project/go-filecoin.git ${FILECOIN_BINARY_VERSION}
+            git push -f https://${GITHUB_TOKEN}@github.com/filecoin-project/venus.git ${FILECOIN_BINARY_VERSION}
       - trigger_infra_build:
           job: deploy_nightly_devnet
           branch: filecoin-nightly
@@ -499,7 +477,7 @@ jobs:
       <<: *user_devnet_param
       <<: *staging_devnet_param
     docker:
-      - image: circleci/golang:1.13.1-stretch
+      - image: circleci/golang:1.14.1-stretch
     resource_class: small
     steps:
       - checkout
@@ -550,7 +528,7 @@ workflows:
             - deps_linux
       - unit_test_linux:
           requires:
-            - deps_linux
+            - build_linux
       - integration_test_linux:
           requires:
             - build_linux
@@ -776,13 +754,26 @@ commands:
         default: false
     steps:
       - run:
+          name: install params file
+          command: |
+            ./venus fetch --size 0
+      - run:
+          name: install statediff globally
+          command: |
+            ## statediff is optional; we succeed even if compilation fails.
+            mkdir -p /tmp/statediff
+            git clone https://github.com/filecoin-project/statediff.git /tmp/statediff
+            cd /tmp/statediff
+            go install ./cmd/statediff || exit 0
+      - run:
           name: Test
           no_output_timeout: 30m
           command: |
             trap "go run github.com/jstemmer/go-junit-report < test-results/go-test-suite/go-test.out > test-results/go-test-suite/go-test-report.xml" EXIT
             export TEST_PACKAGES="$(go list ./... | circleci tests split)"
+
             # Parallelism and timeout set to support medium-class containers, for builds on forked repos.
-            go run ./build test -cover -coverprofile coverage.out -covermode=atomic -timeout=30m -parallel=4 -functional=<< parameters.functional >> -integration=<< parameters.integration >> -sectorbuilder=<< parameters.sector_builder_tests >> -unit=<< parameters.unit >> -v 2>&1 | tee test-results/go-test-suite/go-test.out
+            go run ./build test -cover -coverprofile coverage.out -covermode=atomic -timeout=30m -parallel=4 -functional=<< parameters.functional >>  -integration=<< parameters.integration >> -unit=<< parameters.unit >> -v 2>&1 | tee test-results/go-test-suite/go-test.out
             mkdir -p /tmp/artifacts
             mv coverage.out /tmp/artifacts/coverage.out
       - codecov/upload:
@@ -817,11 +808,11 @@ commands:
         type: string
     steps:
       - run:
-          name: Trigger a build in go-filecoin-infra
+          name: Trigger a build in venus-infra
           command: |
             sudo apt-get install -y curl
             # FILECOIN_BINARY_VERSION must be set in BASH_ENV of job calling this command
-            curl -d build_parameters[FILECOIN_BINARY_VERSION]=${FILECOIN_BINARY_VERSION} -d build_parameters[CIRCLE_JOB]=<< parameters.job >> https://circleci.com/api/v1.1/project/github/filecoin-project/go-filecoin-infra/tree/<< parameters.branch >>?circle-token=$CIRCLE_API_TOKEN
+            curl -d build_parameters[FILECOIN_BINARY_VERSION]=${FILECOIN_BINARY_VERSION} -d build_parameters[CIRCLE_JOB]=<< parameters.job >> https://circleci.com/api/v1.1/project/github/filecoin-project/venus-infra/tree/<< parameters.branch >>?circle-token=$CIRCLE_API_TOKEN
   update_badge:
     parameters:
       filename:
@@ -842,3 +833,4 @@ commands:
       - run:
           name: Update submodules
           command: git submodule update --init --recursive
+
